USE Myproject_2;

# Q1. FIND THOSE HOTEL IN HYDERABAD WHICH HAVE LOW FAIR ?

SELECT HOTEL_BOOKING.CITY,HOTEL_BOOKING.HOTEL_NAME, HOME_STAY_DETAILS.HOME_STAY_NAME,HOTEL_BOOKING.AVL_ROOM  AS HOTEL_AVL_ROOM,
HOME_STAY_DETAILS.AVL_ROOM AS HOMESTAY_AVL_ROOM,HOTEL_BOOKING.HOTEL_FARE,HOME_STAY_DETAILS.FARE AS HOME_STAY_FARE 
FROM HOTEL_BOOKING
JOIN HOME_STAY_DETAILS
ON HOTEL_BOOKING.LOCALITY_ID = HOME_STAY_DETAILS.LOCALITY_ID
JOIN HOME_STAY_ADDRESS
ON HOTEL_BOOKING.CITY = HOME_STAY_ADDRESS.CITY_NAME
WHERE HOTEL_BOOKING.CITY = 'HYDERABAD' AND HOME_STAY_ADDRESS.CITY_NAME = 'HYDERABAD'
GROUP BY HOTEL_BOOKING.HOTEL_NAME 
ORDER BY HOTEL_BOOKING.HOTEL_FARE AND HOME_STAY_DETAILS.FARE ASC ;

# Q2. FIND THOSE HOTEL IN GOA WHICH HAVE LOW FAIR ?


SELECT HOTEL_BOOKING.CITY,HOTEL_BOOKING.HOTEL_NAME, HOME_STAY_DETAILS.HOME_STAY_NAME,HOTEL_BOOKING.AVL_ROOM  AS HOTEL_AVL_ROOM,
HOME_STAY_DETAILS.AVL_ROOM AS HOMESTAY_AVL_ROOM,HOTEL_BOOKING.HOTEL_FARE,HOME_STAY_DETAILS.FARE AS HOME_STAY_FARE 
FROM HOTEL_BOOKING
JOIN HOME_STAY_DETAILS
ON HOTEL_BOOKING.LOCALITY_ID = HOME_STAY_DETAILS.LOCALITY_ID
JOIN HOME_STAY_ADDRESS
ON HOTEL_BOOKING.CITY = HOME_STAY_ADDRESS.CITY_NAME
WHERE HOTEL_BOOKING.CITY = 'GOA' AND HOME_STAY_ADDRESS.CITY_NAME = 'GOA'
GROUP BY HOTEL_BOOKING.HOTEL_NAME 
ORDER BY HOTEL_BOOKING.HOTEL_FARE AND HOME_STAY_DETAILS.FARE ASC ;




# Q3. FIND NEARBY TOURIST LOCATION IN MUMBAI ?

SELECT ACTIVITY_ID.CITY ,ACTIVITY_LOCATION.CITY_ID, ACTIVITY_LOCATION.ACTIVITY, ACTIVITY_LOCATION.LOCATION , ACTIVITY_DETAILS.PERSON_NO ,
 ACTIVITY_DETAILS.ADULTS_FARE , ACTIVITY_DETAILS.CHILDS_FARE , ACTIVITY_DETAILS.PLAN_HOUR , ACTIVITY_RATING.ACTIVITY_RATING
FROM ACTIVITY_ID
JOIN ACTIVITY_LOCATION 
ON  ACTIVITY_ID.CITY_ID = ACTIVITY_LOCATION.CITY_ID
JOIN ACTIVITY_DETAILS 
ON ACTIVITY_LOCATION.CITY_ID = ACTIVITY_DETAILS.CITY_ID
JOIN ACTIVITY_RATING
ON ACTIVITY_DETAILS.CITY_ID = ACTIVITY_RATING.CITY_ID
WHERE ACTIVITY_ID.CITY = 'MUMBAI' ; 



# Q4. FIND NEARBY TOURIST LOCATION IN KOLKATA ?


SELECT ACTIVITY_ID.CITY ,ACTIVITY_LOCATION.CITY_ID, ACTIVITY_LOCATION.ACTIVITY, ACTIVITY_LOCATION.LOCATION , ACTIVITY_DETAILS.PERSON_NO ,
 ACTIVITY_DETAILS.ADULTS_FARE , ACTIVITY_DETAILS.CHILDS_FARE , ACTIVITY_DETAILS.PLAN_HOUR , ACTIVITY_RATING.ACTIVITY_RATING
FROM ACTIVITY_ID
JOIN ACTIVITY_LOCATION 
ON  ACTIVITY_ID.CITY_ID = ACTIVITY_LOCATION.CITY_ID
JOIN ACTIVITY_DETAILS 
ON ACTIVITY_LOCATION.CITY_ID = ACTIVITY_DETAILS.CITY_ID
JOIN ACTIVITY_RATING
ON ACTIVITY_DETAILS.CITY_ID = ACTIVITY_RATING.CITY_ID
WHERE ACTIVITY_ID.CITY = 'KOLKATA' ; 
      
# Q5. LIST OF ALL CITY WHICH HAVE MORE THAN 2 PLACE TO VISIT ?

SELECT DISTINCT CITY
FROM 
	myproject_2.ACTIVITY_ID
GROUP BY CITY
HAVING
      COUNT(CITY) >2 ;
      
      
# Q6. FIND BUS FROM CHENNAI TO PURI FOR MINIMUM FARE IN SLEEPER CLASS?

SELECT BUS_RESERVATION.BUS_ID , BUS_RESERVATION.SERVICE_PROVIDER , BUS_RESERVATION.UP_STATION , 
BUS_RESERVATION.DOWN_STATION , BUS_RESERVATION.DEPT_DATE , BUS_RESERVATION.SEAT_TYPE , MIN(BUS_RESERVATION.FARE) AS FARE ,
BUS_RESERVATION.SEAT_AVL , BUS_ARVL_TIME.ARVL_TIME  , BUS_RATINGS.RATING , BUS_DEPT_TIME.DEPT_TIME , BUS_JOURNEY_HR.JOURNEY_HR
FROM BUS_RESERVATION 
JOIN BUS_ARVL_TIME
ON BUS_RESERVATION.BUS_ID = BUS_ARVL_TIME.BUS_ID
JOIN BUS_DEPT_TIME
ON BUS_ARVL_TIME.BUS_ID = BUS_DEPT_TIME.BUS_ID
JOIN BUS_RATINGS
ON BUS_DEPT_TIME.BUS_ID = BUS_RATINGS.BUS_ID
JOIN BUS_JOURNEY_HR
ON BUS_RATINGS.BUS_ID = BUS_JOURNEY_HR.BUS_ID
WHERE BUS_RESERVATION.UP_STATION = 'CHENNAI' AND BUS_RESERVATION.DOWN_STATION = 'PURI' AND BUS_RESERVATION.SEAT_TYPE = 'SLEEPER' ;      
   SELECT * FROM BUS_RESERVATION   

# Q7. FIND TRAIN BETWEEN MUMBAI TO GOA ON DATE 21TH FEB,2022 .

SELECT TRAIN_DATA.TRAIN_NO,
          TRAIN_DATA.TRAIN_NAME,
              TRAIN_DATA.DEPT_TIME,
			      TRAIN_DATA.ARVL_TIME 
FROM 
     myproject_2.TRAIN_DATA
WHERE
     TRAIN_DATA.UP_STATION='MUMBAI'
     AND TRAIN_DATA.DOWN_STATION='GOA'
     AND TRAIN_DATA.DEPT_DATE='2022-02-21';      
     
     
# Q8. FIND TRAIN BETWEEN AGRA TO PUNE ON DATE 23TH FEB,2022 .

SELECT TRAIN_DATA.TRAIN_NO,
          TRAIN_DATA.TRAIN_NAME,
              TRAIN_DATA.DEPT_TIME,
			      TRAIN_DATA.ARVL_TIME 
FROM 
     myproject_2.TRAIN_DATA
WHERE
     TRAIN_DATA.UP_STATION='AGRA'
     AND TRAIN_DATA.DOWN_STATION='PUNE'
     AND TRAIN_DATA.DEPT_DATE='2022-02-23';      
     
     
# Q9. FIND TRAIN BETWEEN PUNE TO MUMBAI ON DATE 24TH FEB,2022 .

SELECT TRAIN_DATA.TRAIN_NO,
          TRAIN_DATA.TRAIN_NAME,
              TRAIN_DATA.DEPT_TIME,
			      TRAIN_DATA.ARVL_TIME 
FROM 
     myproject_2.TRAIN_DATA
WHERE
     TRAIN_DATA.UP_STATION='PUNE'
     AND TRAIN_DATA.DOWN_STATION='MUMBAI'
     AND TRAIN_DATA.DEPT_DATE='2022-02-24';      
     
      
