USE Myproject_2;

DELIMITER //

create procedure SP_GETDATA()
begin
SELECT HOTEL_BOOKING.CITY,HOTEL_BOOKING.HOTEL_NAME, HOME_STAY_DETAILS.HOME_STAY_NAME,HOTEL_BOOKING.AVL_ROOM  AS HOTEL_AVL_ROOM,
HOME_STAY_DETAILS.AVL_ROOM AS HOMESTAY_AVL_ROOM,HOTEL_BOOKING.HOTEL_FARE,HOME_STAY_DETAILS.FARE AS HOME_STAY_FARE 
FROM HOTEL_BOOKING
JOIN HOME_STAY_DETAILS
ON HOTEL_BOOKING.LOCALITY_ID = HOME_STAY_DETAILS.LOCALITY_ID
JOIN HOME_STAY_ADDRESS
ON HOTEL_BOOKING.CITY = HOME_STAY_ADDRESS.CITY_NAME
WHERE HOTEL_BOOKING.CITY = 'HYDERABAD' AND HOME_STAY_ADDRESS.CITY_NAME = 'HYDERABAD'
GROUP BY HOTEL_BOOKING.HOTEL_NAME 
ORDER BY HOTEL_BOOKING.HOTEL_FARE AND HOME_STAY_DETAILS.FARE ASC ;
END //
DELIMITER ; 

CALL SP_GETDATA();





DELIMITER //

create procedure GET_LOC_CITY()
BEGIN
SELECT ACTIVITY_ID.CITY ,ACTIVITY_LOCATION.CITY_ID, ACTIVITY_LOCATION.ACTIVITY, ACTIVITY_LOCATION.LOCATION , ACTIVITY_DETAILS.PERSON_NO ,
 ACTIVITY_DETAILS.ADULTS_FARE , ACTIVITY_DETAILS.CHILDS_FARE , ACTIVITY_DETAILS.PLAN_HOUR , ACTIVITY_RATING.ACTIVITY_RATING
FROM ACTIVITY_ID
JOIN ACTIVITY_LOCATION 
ON  ACTIVITY_ID.CITY_ID = ACTIVITY_LOCATION.CITY_ID
JOIN ACTIVITY_DETAILS 
ON ACTIVITY_LOCATION.CITY_ID = ACTIVITY_DETAILS.CITY_ID
JOIN ACTIVITY_RATING
ON ACTIVITY_DETAILS.CITY_ID = ACTIVITY_RATING.CITY_ID
WHERE ACTIVITY_ID.CITY = 'MUMBAI' ; 
END //
DELIMITER ;


CALL GET_LOC_CITY();