create database myproject_2;
use myproject_2;

CREATE TABLE `city`
 ( `CITY` varchar(200) NOT NULL,
  PRIMARY KEY (`CITY`)
) ENGINE=InnoDB;

CREATE TABLE `activity_id`
( `CITY_ID` INT NOT NULL,
`CITY` VARCHAR (200),
PRIMARY KEY (`CITY_ID`),
INDEX `CITY_idx` (`CITY` ASC) VISIBLE,
CONSTRAINT `CITY` FOREIGN KEY (`CITY`) REFERENCES `city` (`CITY`)
) ENGINE=InnoDB;

CREATE TABLE `activity_location` 
( `CITY_ID` int NOT NULL,
  `ACTIVITY` varchar(500) NOT NULL,
  `LOCATION` varchar(500) ,
  PRIMARY KEY (`CITY_ID`,`ACTIVITY`),
  CONSTRAINT `FK_AC_LOCATION` FOREIGN KEY (`CITY_ID`) 
  REFERENCES `activity_id` (`CITY_ID`)
) ENGINE=InnoDB;

CREATE TABLE `activity_date`  
(  `CITY_ID` int NOT NULL,
  `ACTIVITY` varchar(500),
  `ACTIVITY_DATE` date NULL,
  PRIMARY KEY (`CITY_ID`),
  INDEX `CITY_ID_idx` (`CITY_ID`,`ACTIVITY`ASC) VISIBLE,
  CONSTRAINT `FK_AC_DATE` FOREIGN KEY (`CITY_ID`)
  REFERENCES `activity_location` (`CITY_ID`)
) ENGINE=InnoDB;

CREATE TABLE `activity_details`
 ( `CITY_ID` int NOT NULL,
  `ACTIVITY` varchar(500),
  `PERSON_NO` int,
  `ADULTS_FARE` int,
  `CHILDS_FARE` int,
  `PLAN_HOUR` int,
  PRIMARY KEY (`CITY_ID`),
  INDEX `FK_AC_DETAILS_idx` (`CITY_ID`,`ACTIVITY` ASC) VISIBLE,
  CONSTRAINT `FK_AC_DETAILS` FOREIGN KEY (`CITY_ID`)
  REFERENCES `activity_location` (`CITY_ID`)
) ENGINE=InnoDB;


CREATE TABLE `activity_rating` 
(  `CITY_ID` int NOT NULL,
  `ACTIVITY` varchar(500) ,
  `ACTIVITY_RATING` int ,
  PRIMARY KEY (`CITY_ID`),
  INDEX `FK_AC_RATING_idx` (`CITY_ID`,`ACTIVITY` ASC) VISIBLE,
  CONSTRAINT `FK_AC_RATING` FOREIGN KEY (`CITY_ID`) 
  REFERENCES `activity_location` (`CITY_ID`)
) ENGINE=InnoDB;

CREATE TABLE `bus_id` 
( `BUS_ID` int NOT NULL,
  `SERVICE_PROVIDER` varchar(200) NOT NULL,
  PRIMARY KEY (`BUS_ID`,`SERVICE_PROVIDER`)
) ENGINE=InnoDB ;

CREATE TABLE `bus_ratings`
 ( `BUS_ID` int NOT NULL,
  `SERVICE_PROVIDER` varchar(200) ,
  `SEAT_TYPE` varchar(45) ,
  `RATING` float8 ,
  PRIMARY KEY (`BUS_ID`,`SERVICE_PROVIDER`,`SEAT_TYPE`,`RATING`),
  INDEX `FK_BUS_RATING_idx` (`BUS_ID`,`SERVICE_PROVIDER` ASC) VISIBLE,
  CONSTRAINT `FK_BUS_RATING` FOREIGN KEY (`BUS_ID`, `SERVICE_PROVIDER`) 
  REFERENCES `bus_id` (`BUS_ID`, `SERVICE_PROVIDER`)
) ENGINE=InnoDB ;

CREATE TABLE `bus_arvl_time`
 ( `BUS_ID` int NOT NULL,
  `SERVICE_PROVIDER` varchar(200) ,
  `BUS_DOWN_STATION` varchar(200) ,
  `ARVL_TIME` time ,
  PRIMARY KEY  (`BUS_ID`,`SERVICE_PROVIDER`,`BUS_DOWN_STATION`,`ARVL_TIME`),
  INDEX `FK_BUS_UP_idx` (`BUS_DOWN_STATION` ASC) VISIBLE,
  INDEX `FK_BUS_ARVL` (`BUS_ID`,`SERVICE_PROVIDER` ASC) VISIBLE,
  CONSTRAINT `FK_BUS_ARVL` FOREIGN KEY (`BUS_ID`, `SERVICE_PROVIDER`) REFERENCES `bus_id` (`BUS_ID`, `SERVICE_PROVIDER`),
  CONSTRAINT `FK_BUS_DOWN` FOREIGN KEY (`BUS_DOWN_STATION`) REFERENCES `city` (`CITY`)
) ENGINE=InnoDB ;

CREATE TABLE `bus_dept_time` 
( `BUS_ID` int NOT NULL,
  `SERVICE_PROVIDER` varchar(200) ,
  `BUS_UP_STATION` varchar(200) NOT NULL,
  `DEPT_TIME` time ,
  PRIMARY KEY (`BUS_ID`,`BUS_UP_STATION`,`SERVICE_PROVIDER`,`DEPT_TIME`),
  INDEX `FK_BUS_UP_idx` (`BUS_UP_STATION` ASC) VISIBLE,
  INDEX `FK_BUS_DEPT` (`BUS_ID`,`SERVICE_PROVIDER` ASC) VISIBLE,
  CONSTRAINT `FK_BUS_DEPT` FOREIGN KEY (`BUS_ID`, `SERVICE_PROVIDER`) REFERENCES `bus_id` (`BUS_ID`, `SERVICE_PROVIDER`),
  CONSTRAINT `FK_BUS_UP` FOREIGN KEY (`BUS_UP_STATION`) REFERENCES `city` (`CITY`)
) ENGINE=InnoDB ;

CREATE TABLE `bus_journey_hr` 
( `BUS_ID` int NOT NULL,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `JOURNEY_HR` int ,
  PRIMARY KEY (`BUS_ID`,`UP_STATION`,`DOWN_STATION`, `JOURNEY_HR`),
  INDEX `FK_SOURCES_idx` (`UP_STATION`,`DOWN_STATION` ASC) VISIBLE,
  INDEX `FK_JOURNEY_idx` (`BUS_ID`,`UP_STATION` ASC) VISIBLE,
  CONSTRAINT `FK_JOURNEY` FOREIGN KEY (`BUS_ID`, `UP_STATION`) 
  REFERENCES `bus_dept_time` (`BUS_ID`, `BUS_UP_STATION`)
) ENGINE=InnoDB ;

CREATE TABLE `bus_reservation`
 ( `BUS_ID` int NOT NULL,
   `SERVICE_PROVIDER` varchar(200) ,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `DEPT_DATE` date ,
  `SEAT_TYPE` varchar(100) ,
  `FARE` int ,
  `SEAT_AVL` float8,
  PRIMARY KEY (`BUS_ID`,`SERVICE_PROVIDER`,`UP_STATION`,`SEAT_TYPE`, `DEPT_DATE`,`down_station` ),
  INDEX `FK_BUS_RE_idx` (`BUS_ID`,`UP_STATION` ASC) VISIBLE,
  CONSTRAINT `FK_BUS_RE` FOREIGN KEY (`BUS_ID`, `UP_STATION`) 
  REFERENCES `bus_dept_time` (`BUS_ID`, `BUS_UP_STATION`)
) ENGINE=InnoDB ;

CREATE TABLE `flight_details` 
( `FLIGHT_ID` varchar(50) NOT NULL,
  `FLIGHT_SERVICES_PROVIDER` varchar(200) NOT NULL,
  PRIMARY KEY (`FLIGHT_ID`,`FLIGHT_SERVICES_PROVIDER`)
) ENGINE=InnoDB ;

CREATE TABLE `flight_arvl_time` 
( `FLIGHT_ID` varchar(50) NOT NULL,
  `FLIGHT_SERVICES_PROVIDER` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `ARVL_TIME` time ,
  PRIMARY KEY (`FLIGHT_ID`,`DOWN_STATION`,`ARVL_TIME`),
  INDEX `FK_FLIGHT_idx` (`FLIGHT_ID`,`FLIGHT_SERVICES_PROVIDER` ASC) VISIBLE,
  CONSTRAINT `FK_FLIGHT` FOREIGN KEY (`FLIGHT_ID`, `FLIGHT_SERVICES_PROVIDER`) 
  REFERENCES `flight_details` (`FLIGHT_ID`, `FLIGHT_SERVICES_PROVIDER`)
) ENGINE=InnoDB ;

CREATE TABLE `flight_dept_time` 
( `FLIGHT_ID` varchar(50) NOT NULL,
  `FLIGHT_SERVICES_PROVIDER` varchar(200) ,
  `UP_STATION` varchar(200) ,
  `DEPT_TIME` time ,
  PRIMARY KEY (`FLIGHT_ID`,`UP_STATION`,`DEPT_TIME`),
  INDEX `FLIGHT_DEPT_TIME_idx` (`FLIGHT_ID`,`FLIGHT_SERVICES_PROVIDER` ASC) VISIBLE,
  INDEX `FLIGHT_CITY_idx` (`UP_STATION` ASC) VISIBLE,
  CONSTRAINT `FLIGHT_CITY` FOREIGN KEY (`UP_STATION`) REFERENCES `city` (`CITY`),
  CONSTRAINT `FLIGHT_DEPT_TIME` FOREIGN KEY (`FLIGHT_ID`, `FLIGHT_SERVICES_PROVIDER`) 
  REFERENCES `flight_details` (`FLIGHT_ID`, `FLIGHT_SERVICES_PROVIDER`)
) ENGINE=InnoDB ;

CREATE TABLE `flight_dept_date` 
( `FLIGHT_ID` varchar(50) NOT NULL,
  `FLIGHT_DEPT_DATE` date ,
  `FLIGHT_ARVL_DATE` date ,
  PRIMARY KEY (`FLIGHT_ID`,  `FLIGHT_DEPT_DATE`,`FLIGHT_ARVL_DATE` ),
  CONSTRAINT `FLIGHT_DATE` FOREIGN KEY (`FLIGHT_ID`) REFERENCES `flight_details` (`FLIGHT_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `flight_journey_hr` 
( `FLIGHT_ID` varchar(50) NOT NULL,
  `FLIGHT_SERVICES_PROVIDER` varchar(200) ,
  `UP_STATION` varchar(200) NOT NULL,
  `DOWN_STATION` varchar(200) NOT NULL,
  `JOURNEY_HR` time ,
  PRIMARY KEY (`FLIGHT_ID`,`UP_STATION`,`DOWN_STATION`,`JOURNEY_HR`),
  INDEX `FLIGHT_JR_HR_idx` (`FLIGHT_ID`,`FLIGHT_SERVICES_PROVIDER` ASC) VISIBLE,
  INDEX `FLIGHT_JR_CITY_idx` (`UP_STATION`,`DOWN_STATION` ASC) VISIBLE,
  CONSTRAINT `FLIGHT_CITY_JR` FOREIGN KEY (`UP_STATION`) REFERENCES `city` (`CITY`),
  CONSTRAINT `FLIGHT_JR` FOREIGN KEY (`FLIGHT_ID`, `FLIGHT_SERVICES_PROVIDER`) 
  REFERENCES `flight_details` (`FLIGHT_ID`, `FLIGHT_SERVICES_PROVIDER`)
) ENGINE=InnoDB ;

CREATE TABLE `flight_economy_class` 
( `FLIGHT_ID` varchar(50) NOT NULL,
  `FLIGHT_SERVICES_PROVIDER` varchar(200) ,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `CLASS` varchar(200) ,
  `FARE` int ,
  PRIMARY KEY (`FLIGHT_ID`,`UP_STATION`,`DOWN_STATION`),
  INDEX `FLIGHT_EC_CLASS_idx` (`UP_STATION`,`DOWN_STATION` ASC) VISIBLE,
  INDEX `FLIGHT_JR_EC_CLASS_idx` (`FLIGHT_ID`,`FLIGHT_SERVICES_PROVIDER` ASC) VISIBLE,
  INDEX `FK_EC_idx` (`FLIGHT_ID`,`UP_STATION`,`DOWN_STATION` ASC) VISIBLE,
  CONSTRAINT `FK_EC` FOREIGN KEY (`FLIGHT_ID`, `UP_STATION`, `DOWN_STATION`) 
  REFERENCES `flight_journey_hr` (`FLIGHT_ID`, `UP_STATION`, `DOWN_STATION`)
) ENGINE=InnoDB ;

CREATE TABLE `flight_pre_economy` 
(  `FLIGHT_ID` varchar(50) NOT NULL,
  `FLIGHT_SERVICES_PROVIDER` varchar(200) ,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `CLASS` varchar(200) ,
  `FARE` int ,
  PRIMARY KEY (`FLIGHT_ID`, `UP_STATION`,  `DOWN_STATION`),
  INDEX `FK_PRE_EC_idx` (`FLIGHT_ID`,`UP_STATION`,`DOWN_STATION` ASC) VISIBLE,
  CONSTRAINT `FK_PRE_EC` FOREIGN KEY (`FLIGHT_ID`, `UP_STATION`, `DOWN_STATION`) 
  REFERENCES `flight_journey_hr` (`FLIGHT_ID`, `UP_STATION`, `DOWN_STATION`),
  CONSTRAINT `FLIGHT_PRE_EC` FOREIGN KEY (`FLIGHT_ID`, `UP_STATION`, `DOWN_STATION`) 
  REFERENCES `flight_journey_hr` (`FLIGHT_ID`, `UP_STATION`, `DOWN_STATION`)
) ENGINE=InnoDB ;

CREATE TABLE `flight_first_class` 
( `FLIGHT_ID` varchar(50) NOT NULL,
  `FLIGHT_SERVICES_PROVIDER` varchar(200) ,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `CLASS` varchar(200) ,
  `FARE` int ,
  PRIMARY KEY (`FLIGHT_ID`, `UP_STATION`,`DOWN_STATION` ),
  INDEX `FK_FIRST_CLASS_idx` (`FLIGHT_ID`,`UP_STATION`,`DOWN_STATION` ASC) VISIBLE,
  CONSTRAINT `FK_FIRST-CLASS` FOREIGN KEY (`FLIGHT_ID`, `UP_STATION`, `DOWN_STATION`) 
  REFERENCES `flight_journey_hr` (`FLIGHT_ID`, `UP_STATION`, `DOWN_STATION`)
) ENGINE=InnoDB ;

CREATE TABLE `flight_business_class` 
( `FLIGHT_ID` varchar(50) NOT NULL,
  `FLIGHT_SERVICES_PROVIDER` varchar(200) ,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `CLASS` varchar(200) ,
  `FARE` int ,
  PRIMARY KEY (`FLIGHT_ID`,`UP_STATION`, `DOWN_STATION`),
  INDEX `FLIGHT_b_CLASS_idx` (`FLIGHT_ID`,`UP_STATION`,`DOWN_STATION` ASC) VISIBLE,
  CONSTRAINT `FLIGHT_b_CLASS` FOREIGN KEY (`FLIGHT_ID`, `UP_STATION`, `DOWN_STATION`) 
  REFERENCES `flight_journey_hr` (`FLIGHT_ID`, `UP_STATION`, `DOWN_STATION`)
) ENGINE=InnoDB ;

CREATE TABLE `home_stay_ratings` 
( `LOCALITY_ID` int NOT NULL,
  `HOME_STAY_NAME` varchar(200) NOT NULL,
  `HOME_STAY_RATING` float8 ,
  PRIMARY KEY (`LOCALITY_ID`,`HOME_STAY_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `home_stay_details` 
( `LOCALITY_ID` int NOT NULL,
  `HOME_STAY_NAME` varchar(200) ,
  `HOME_STAY_ROOM_TYPE` varchar(200) ,
  `AVL_ROOM` int ,
  `GUEST` int ,
  `BED_TYPE` varchar(50) ,
  `FARE` int ,
  `ROOM_SERVICE` varchar(45) ,
  PRIMARY KEY(`LOCALITY_ID`,`HOME_STAY_NAME`,`HOME_STAY_ROOM_TYPE`,`BED_TYPE`),
  INDEX `FK_HOMESTAY_idx` (`LOCALITY_ID`,`HOME_STAY_NAME` ASC) VISIBLE,
  CONSTRAINT `FK_HOMESTAY` FOREIGN KEY (`LOCALITY_ID`, `HOME_STAY_NAME`) 
  REFERENCES `home_stay_ratings` (`LOCALITY_ID`, `HOME_STAY_NAME`)
) ENGINE=InnoDB;

CREATE TABLE `home_stay_room_size` 
( `LOCALITY_ID` int NOT NULL,
  `HOME_STAY_NAME` varchar(200) ,
  `HOME_ROOM_SIZE` int ,
  PRIMARY KEY (`LOCALITY_ID`,`HOME_STAY_NAME`,`HOME_ROOM_SIZE` ),
  INDEX `FK_HOME_STAY_SIZE_idx` (`LOCALITY_ID`,`HOME_STAY_NAME` ASC) VISIBLE,
  CONSTRAINT `FK_HOME_STAY_SIZE` FOREIGN KEY (`LOCALITY_ID`, `HOME_STAY_NAME`) 
  REFERENCES `home_stay_ratings` (`LOCALITY_ID`, `HOME_STAY_NAME`)
) ENGINE=InnoDB ; 

CREATE TABLE `home_stay_facility` 
( `LOCALITY_ID` int NOT NULL,
  `HOME_STAY_NAME` varchar(150) ,
  `LOCALITY_NAME` varchar(150) ,
  `ROOM_TYPE` varchar(100) ,
  `ROOM_FACILITY` varchar(100) ,
  PRIMARY KEY (`LOCALITY_ID`,`HOME_STAY_NAME`,`LOCALITY_NAME`,`ROOM_TYPE`),
  INDEX `FK_HOME_STAY_FC_idx` (`LOCALITY_ID`,`HOME_STAY_NAME` ASC) VISIBLE,
  CONSTRAINT `FK_HOME_STAY_FC` FOREIGN KEY (`LOCALITY_ID`, `HOME_STAY_NAME`) 
  REFERENCES `home_stay_ratings` (`LOCALITY_ID`, `HOME_STAY_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `home_stay_address`
 ( `LOCALITY_ID` int NOT NULL,
  `HOME_STAY_NAME` varchar(200) ,
  `CITY_NAME` varchar(200) ,
  `LOCALITY_NAME` varchar(200) ,
  `LANDMARK` varchar(200) ,
  PRIMARY KEY (`LOCALITY_ID`,`HOME_STAY_NAME`,`LOCALITY_NAME`, `CITY_NAME`),
  INDEX `FK_HOME_STAY_idx` (`LOCALITY_ID`,`HOME_STAY_NAME` ASC) VISIBLE,
  INDEX `FK_HOME_CITY_idx` (`CITY_NAME` ASC) VISIBLE,
  CONSTRAINT `FK_HOME_CITY` FOREIGN KEY (`CITY_NAME`) REFERENCES `city` (`CITY`),
  CONSTRAINT `FK_HOME_STAY` FOREIGN KEY (`LOCALITY_ID`, `HOME_STAY_NAME`) 
  REFERENCES `home_stay_ratings` (`LOCALITY_ID`, `HOME_STAY_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `home_stay_check_in` 
( `LOCALITY_ID` int NOT NULL,
  `HOME_STAY_NAME` varchar(200) ,
  `CITY_NAME` varchar(200) ,
  `CHECK_IN_DATE` date ,
  `CHECK_IN_TIME` time ,
  `CHECK_OUT_TIME` time ,
  PRIMARY KEY (`LOCALITY_ID`,`HOME_STAY_NAME`),
  INDEX `FK_HOME_STAY_CHECK_idx` (`LOCALITY_ID`,`HOME_STAY_NAME` ASC) VISIBLE,
  INDEX `FK_CITY_CHECK_idx` (`CITY_NAME` ASC) VISIBLE,
  CONSTRAINT `FK_CITY_CHECK` FOREIGN KEY (`CITY_NAME`) REFERENCES `city` (`CITY`),
  CONSTRAINT `FK_HOME_STAY_CHECK` FOREIGN KEY (`LOCALITY_ID`, `HOME_STAY_NAME`)
  REFERENCES `home_stay_ratings` (`LOCALITY_ID`, `HOME_STAY_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `hotel_details` 
( `LOCALITY_ID` int NOT NULL,
  `CITY` varchar(200) NOT NULL,
  `HOTEL_NAME` varchar(200) NOT NULL,
  `HOTEL_LOCALITY` varchar(200) NOT NULL,
  PRIMARY KEY (`LOCALITY_ID`,`CITY`,`HOTEL_NAME`,`HOTEL_LOCALITY`),
  INDEX `FK_CITY_DETAILS_idx` (`CITY` ASC) VISIBLE,
  CONSTRAINT `FK_CITY_DETAILS` FOREIGN KEY (`CITY`) REFERENCES `city` (`CITY`)
) ENGINE=InnoDB ;

CREATE TABLE `hotel_address` 
( `LOCALITY_ID` int NOT NULL,
  `CITY` varchar(200) ,
  `HOTEL_NAME` varchar(200) ,
  `HOTEL_LOCALITY` varchar(200) ,
  `STREET_ADDRESS` varchar(500) ,
   PRIMARY KEY (`LOCALITY_ID`,`CITY`,`HOTEL_NAME`,`HOTEL_LOCALITY`),
  INDEX `FK_HOTEL_AD_idx` (`LOCALITY_ID`,`CITY`,`HOTEL_NAME`,`HOTEL_LOCALITY` ASC) VISIBLE,
  CONSTRAINT `FK_HOTEL_AD` FOREIGN KEY (`LOCALITY_ID`, `CITY`, `HOTEL_NAME`, `HOTEL_LOCALITY`) 
  REFERENCES `hotel_details` (`LOCALITY_ID`, `CITY`, `HOTEL_NAME`, `HOTEL_LOCALITY`)
) ENGINE=InnoDB ;

CREATE TABLE `hotel_booking` 
( `LOCALITY_ID` int NOT NULL,
  `CITY` varchar(200) ,
  `HOTEL_NAME` varchar(200) ,
  `LOCALITY` varchar(200) ,
  `ROOM_SERVICES` varchar(45) ,
  `CHECK_IN_DATE` date ,
  `AVL_ROOM` int ,
  `HOTEL_FARE` int ,
  `CHECK_IN_TIME` time ,
  `CHECK_OUT_TIME` time ,
  PRIMARY KEY (`LOCALITY_ID`,`CITY`,`HOTEL_NAME`,`LOCALITY`),
  INDEX `FK_HOTEL_BOOKING_idx` (`LOCALITY_ID`,`CITY`,`HOTEL_NAME`,`LOCALITY` ASC) VISIBLE,
  CONSTRAINT `FK_HOTEL_BOOKING` FOREIGN KEY (`LOCALITY_ID`, `CITY`, `HOTEL_NAME`, `LOCALITY`) 
  REFERENCES `hotel_details` (`LOCALITY_ID`, `CITY`, `HOTEL_NAME`, `HOTEL_LOCALITY`)
) ENGINE=InnoDB ;

CREATE TABLE `hotel_rating` 
( `LOCALITY_ID` int NOT NULL,
  `CITY` varchar(200) ,
  `HOTEL_NAME` varchar(200) ,
  `HOTEL_RATING` float8 ,
  PRIMARY KEY (`LOCALITY_ID`,`CITY`,`HOTEL_NAME`),
  INDEX `FK_HOTEL_RATING_idx` (`LOCALITY_ID`,`CITY`,`HOTEL_NAME` ASC) VISIBLE,
  CONSTRAINT `FK_HOTEL_RATING` FOREIGN KEY (`LOCALITY_ID`, `CITY`, `HOTEL_NAME`) 
  REFERENCES `hotel_details` (`LOCALITY_ID`, `CITY`, `HOTEL_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `hotel_room_area` 
( `LOCALITY_ID` int NOT NULL,
  `CITY` varchar(200) ,
  `HOTEL_NAME` varchar(200) ,
  `HOTEL_ROOM_AREA` int ,
  PRIMARY KEY (`LOCALITY_ID`,`CITY`,`HOTEL_NAME`),
  INDEX `FK_HOTEL_AREA_idx` (`LOCALITY_ID`,`CITY`,`HOTEL_NAME` ASC) VISIBLE,
  CONSTRAINT `FK_HOTEL_AREA` FOREIGN KEY (`LOCALITY_ID`, `CITY`, `HOTEL_NAME`) 
  REFERENCES `hotel_details` (`LOCALITY_ID`, `CITY`, `HOTEL_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `hotel_room_type`
 ( `LOCALITY_ID` int NOT NULL,
  `CITY` varchar(200) ,
  `HOTEL_NAME` varchar(200) ,
  `HOTEL_ROOM_TYPE` varchar(200) ,
  PRIMARY KEY (`LOCALITY_ID`,`CITY`,`HOTEL_NAME`),
  INDEX `FK_HOTEL_ROOM_TYPE_idx` (`LOCALITY_ID`,`CITY`,`HOTEL_NAME` ASC) VISIBLE,
  CONSTRAINT `FK_HOTEL_ROOM_TYPE` FOREIGN KEY (`LOCALITY_ID`, `CITY`, `HOTEL_NAME`) 
  REFERENCES `hotel_details` (`LOCALITY_ID`, `CITY`, `HOTEL_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `train_details` 
( `TRAIN_NO` int NOT NULL,
  `TRAIN_NAME` varchar(200) NOT NULL,
  PRIMARY KEY (`TRAIN_NO`,`TRAIN_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `train_dept_date` 
( `TRAIN_NO` int NOT NULL,
  `DEPT_DATE` date NOT NULL,
  PRIMARY KEY (`TRAIN_NO`,`DEPT_DATE`),
  CONSTRAINT `FK_TRAIN_DATE` FOREIGN KEY (`TRAIN_NO`) 
  REFERENCES `train_details` (`TRAIN_NO`)
) ENGINE=InnoDB ;

CREATE TABLE `train_dept_time` 
( `TRAIN_NO` int NOT NULL,
  `UP_STATION` varchar(200) ,
  `DEPT_TIME` time ,
  PRIMARY KEY (`TRAIN_NO`,`UP_STATION`),
  INDEX `FK_TRAIN_TIME_idx` (`TRAIN_NO` ASC) VISIBLE,
  INDEX `FK_TRIAN_DEPT_idx` (`UP_STATION` ASC) VISIBLE,
  CONSTRAINT `FK_TRAIN_DEPT` FOREIGN KEY (`TRAIN_NO`) REFERENCES `train_details` (`TRAIN_NO`),
  CONSTRAINT `FK_TRIAN_DEPT` FOREIGN KEY (`UP_STATION`) REFERENCES `city` (`CITY`)
) ENGINE=InnoDB ;

CREATE TABLE `train_arvl_time` 
( `TRAIN_NO` int NOT NULL,
  `DOWN_STATION` varchar(200) ,
  `ARVL_TIME` time ,
  PRIMARY KEY (`TRAIN_NO`,`DOWN_STATION`),
  INDEX `FK_TRAIN_ARVL_idx` (`TRAIN_NO`ASC) VISIBLE,
  INDEX `FK_CITY_ARL_idx` (`DOWN_STATION` ASC) VISIBLE,
  CONSTRAINT `FK_CITY_ARL` FOREIGN KEY (`DOWN_STATION`) REFERENCES `city` (`CITY`),
  CONSTRAINT `FK_TRAIN_ARVL` FOREIGN KEY (`TRAIN_NO`) REFERENCES `train_details` (`TRAIN_NO`)
) ENGINE=InnoDB ;

CREATE TABLE `train_journey_hr` 
( `TRAIN_NO` int NOT NULL,
  `TRAIN_NAME` varchar(200) NOT NULL,
  `UP_STATION` varchar(200) NOT NULL,
  `DOWN_STATION` varchar(200) NOT NULL,
  `JOURNEY_HR` time ,
  PRIMARY KEY (`TRAIN_NO`,`DOWN_STATION`,`UP_STATION`,`TRAIN_NAME`),
  INDEX `FK_TRAIN_JR_HR_idx` (`TRAIN_NO`,`TRAIN_NAME`,`UP_STATION` ASC) VISIBLE,
  INDEX `TRAIN_CITY_idx` (`UP_STATION` ASC) VISIBLE,
  INDEX `TRAIN_JRD_idx` (`DOWN_STATION` ASC) VISIBLE,
  CONSTRAINT `TRAIN_CITY` FOREIGN KEY (`UP_STATION`) REFERENCES `city` (`CITY`),
  CONSTRAINT `TRAIN_DOWN_CITY` FOREIGN KEY (`DOWN_STATION`) REFERENCES `city` (`CITY`),
  CONSTRAINT `TRAIN_JR` FOREIGN KEY (`TRAIN_NO`, `TRAIN_NAME`) REFERENCES `train_details` (`TRAIN_NO`, `TRAIN_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `train_2s_reservation`
 (`TRAIN_NO` int NOT NULL,
  `TRAIN_NAME` varchar(200) ,
  `DEPT_DATE` date ,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `CLASS` varchar(45) ,
  `FARE` int ,
  `SEATS` int ,
  `STATUS` varchar(45) ,
  PRIMARY KEY (`TRAIN_NO`,`dept_date`,`up_station`,`down_station`),
  INDEX `TRAIN_2S_idx` (`TRAIN_NO`,`TRAIN_NAME`ASC) VISIBLE,
  INDEX `FK_DATE_2S_idx` (`DEPT_DATE` ASC) VISIBLE,
  CONSTRAINT `TRAIN_2S` FOREIGN KEY (`TRAIN_NO`, `TRAIN_NAME`) 
  REFERENCES `train_journey_hr` (`TRAIN_NO`, `TRAIN_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `train_sl_reservation` 
( `TRAIN_NO` int NOT NULL,
  `TRAIN_NAME` varchar(200) ,
  `DEPT_DATE` date ,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `CLASS` varchar(45) ,
  `FARE` int ,
  `SEATS` int ,
  `STATUS` varchar(45) ,
  PRIMARY KEY (`TRAIN_NO`,`dept_date`,`up_station`,`down_station`),
  INDEX `FK_TRAIN_SL_idx` (`TRAIN_NO`,`TRAIN_NAME` ASC) VISIBLE,
  INDEX `FK_DATE_SL_idx` (`DEPT_DATE` ASC) VISIBLE,
  CONSTRAINT `FK_TRAIN_SL` FOREIGN KEY (`TRAIN_NO`, `TRAIN_NAME`) 
  REFERENCES `train_journey_hr` (`TRAIN_NO`, `TRAIN_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `train_3a_reservation` 
( `TRAIN_NO` int NOT NULL,
  `TRAIN_NAME` varchar(200) ,
  `DEPT_DATE` date ,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `CLASS` varchar(45) ,
  `FARE` int ,
  `SEATS` int ,
  `STATUS` varchar(45) ,
  PRIMARY KEY (`TRAIN_NO`,`dept_date`,`up_station`,`down_station`),
  INDEX `TRIAN_3A_idx` (`TRAIN_NO`,`TRAIN_NAME` ASC) VISIBLE,
  INDEX `FK_DATE_3A_idx` (`DEPT_DATE` ASC) VISIBLE,
  CONSTRAINT `TRIAN_3A` FOREIGN KEY (`TRAIN_NO`, `TRAIN_NAME`) 
  REFERENCES `train_journey_hr` (`TRAIN_NO`, `TRAIN_NAME`)
) ENGINE=InnoDB ;

CREATE TABLE `train_2a_reservation` 
( `TRAIN_NO` int NOT NULL,
  `TRAIN_NAME` varchar(200) ,
  `DEPT_DATE` date ,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `CLASS` varchar(45) ,
  `FARE` int ,
  `SEATS` int ,
  `STATUS` varchar(45) ,
  PRIMARY KEY (`TRAIN_NO`,`dept_date`,`up_station`,`down_station`),
  INDEX `FK_TRAIN_2A_idx` (`TRAIN_NO`,`TRAIN_NAME` ASC) VISIBLE,
  INDEX `FK_DATE_2A_idx` (`DEPT_DATE` ASC) VISIBLE,
  CONSTRAINT `TRAIN_2A` FOREIGN KEY (`TRAIN_NO`, `TRAIN_NAME`) 
  REFERENCES `train_journey_hr` (`TRAIN_NO`, `TRAIN_NAME`)
  ) ENGINE=InnoDB ;

CREATE TABLE `train_1a_reservation` 
( `TRAIN_NO` int NOT NULL,
  `TRAIN_NAME` varchar(200) ,
  `DEPT_DATE` date ,
  `UP_STATION` varchar(200) ,
  `DOWN_STATION` varchar(200) ,
  `CLASS` varchar(45) ,
  `FARE` int ,
  `SEATS` int ,
  `STATUS` varchar(45) ,
  PRIMARY KEY (`TRAIN_NO`,`dept_date`,`up_station`,`down_station`),
  INDEX `TRIAN_1A_idx` (`TRAIN_NO`,`TRAIN_NAME` ASC) VISIBLE,
  INDEX `FK_DATE_idx` (`DEPT_DATE` ASC) VISIBLE,
  CONSTRAINT `TRIAN_1A` FOREIGN KEY (`TRAIN_NO`, `TRAIN_NAME`)
  REFERENCES `train_journey_hr` (`TRAIN_NO`, `TRAIN_NAME`)
) ENGINE=InnoDB ;


USE MyProject_2;


INSERT INTO `city` (`CITY`) VALUES ('AGRA');
INSERT INTO `city` (`CITY`) VALUES ('AMRITSAR');
INSERT INTO `city` (`CITY`) VALUES ('BENGALURU');
INSERT INTO `city` (`CITY`) VALUES ('GAYA');
INSERT INTO `city` (`CITY`) VALUES ('PURI');
INSERT INTO `city` (`CITY`) VALUES ('GOA');
INSERT INTO `city` (`CITY`) VALUES ('HYDERABAD');
INSERT INTO `city` (`CITY`) VALUES ('JAIPUR');
INSERT INTO `city` (`CITY`) VALUES ('JODHPUR');
INSERT INTO `city` (`CITY`) VALUES ('KOLKATA');
INSERT INTO `city` (`CITY`) VALUES ('NEW DELHI');
INSERT INTO `city` (`CITY`) VALUES ('CHENNAI');
INSERT INTO `city` (`CITY`) VALUES ('MUMBAI');
INSERT INTO `city` (`CITY`) VALUES ('PUNE');

